# orchestrator_ui.py
"""
智慧審核式資料流生產線 UI
支援「逐步審核模式 (Human-in-the-Loop)」與「全自動模式」兩種運作方式。

狀態機流程：idle → arch_done → scl_done → all_done
"""
import streamlit as st
import pandas as pd
import io
import re
import os
import json
from workflows.orchestrator import (
    prepare_pipeline_input, run_step_panel_engineering, run_step_architecture, run_step_scl,
    run_step_hmi, run_automated_pipeline, run_step_chaos_testing, run_step_tech_writer
)
from services.tia_exporter import TIAExporter
from core.input_guard import validate_input


# ==========================================
#  主渲染入口
# ==========================================
def render(client, collection):
    st.markdown("### 🧩 智慧審核式資料流生產線")
    st.markdown(
        "AI 代理人們將依次為您設計 **[硬體架構]** ➡️ **[SCL 程式碼]** ➡️ **[HMI 佈局]**。"
        "您可以在每個步驟完成後審核、提出修改意見，或選擇全自動模式一鍵完成。"
    )

    # ---------- 初始化狀態機 ----------
    _defaults = {
        "pipeline_step": "idle",
        "pipeline_input": "",
        "pipeline_res": {},
        "pipeline_target_ver": "V17",
        "pipeline_input_area": "",
        "global_tia_mode": "🔄 更新本機既有專案",
        "global_tia_proj": r"C:\Users\cangk\Documents\Automation\MyTestProject.ap17",
        "global_tia_plc": "PLC_1",
        "global_tia_dir": r"C:\Users\cangk\Documents\Automation",
        "global_tia_new_name": "AutoGenerated_Project",
    }
    for k, v in _defaults.items():
        if k not in st.session_state:
            st.session_state[k] = v

    # 若有 INFEASIBLE 警告尚未處理，優先顯示並中斷後續渲染
    if st.session_state.get("guard_infeasible_pending"):
        guard = st.session_state["guard_infeasible_pending"]
        st.markdown(
            """
            <div style='border:2px solid #ff9800;border-radius:12px;
                        padding:18px 22px;background:rgba(255,152,0,0.08);margin-bottom:16px;'>
            <h4 style='color:#ff9800;margin-top:0;'>⚠️ 工程師顧問警告：需求存在技術矛盾</h4>
            """,
            unsafe_allow_html=True
        )
        st.warning(f"**❌ 偵測到的問題：**\n\n{guard.reason}")
        if guard.suggestion:
            st.info(f"**💡 AI 建議的修正方案：**\n\n{guard.suggestion}")
        st.markdown("</div>", unsafe_allow_html=True)

        col_adopt, col_force, col_cancel = st.columns([2, 2, 1])
        with col_adopt:
            if st.button("✅ 採納建議，修改後重新輸入", type="primary", use_container_width=True, key="guard_adopt"):
                # 把建議預填回輸入框，讓使用者修改後重新提交
                st.session_state.pipeline_input_area = (
                    f"【根據 AI 建議修改】\n原始需求：{guard.reason}\n\n修正建議：{guard.suggestion}\n\n"
                    "請在此根據上述建議修改後，重新描述您的需求："
                )
                st.session_state.guard_infeasible_pending = None
                st.rerun()
        with col_force:
            if st.button("⚡ 強制繼續（忽略警告）", use_container_width=True, key="guard_force"):
                # 清除警告，繼續跑已暫存的流程
                pending = st.session_state.pop("guard_infeasible_pipeline", {})
                st.session_state.guard_infeasible_pending = None
                _launch_pipeline(
                    client, collection,
                    pending.get("user_input", ""),
                    pending.get("pdf_bytes"),
                    pending.get("tag_table_str"),
                    pending.get("target_version", "V17"),
                    pending.get("start_auto", False),
                )
        with col_cancel:
            if st.button("🔙 取消", use_container_width=True, key="guard_cancel"):
                st.session_state.guard_infeasible_pending = None
                st.rerun()
        return  # 顯示警告卡時，不渲染輸入區

    step = st.session_state.pipeline_step

    # ---------- 進度條 (非 idle 時顯示) ----------
    if step != "idle":
        _render_progress(step)
        st.divider()

    # ---------- 狀態路由 ----------
    if step == "idle":
        _render_idle(client, collection)
    elif step == "panel_done":
        _render_panel_review(client, collection)
    elif step == "arch_done":
        _render_arch_review(client, collection)
    elif step == "scl_done":
        _render_scl_review(client, collection)
    elif step == "archaeologist_done":
        _render_archaeologist_review(client, collection)
    elif step == "all_done":
        _render_all_done(client, collection)


# ==========================================
#  進度指示器
# ==========================================
def _render_progress(step):
    step_num = {"panel_done": 1, "arch_done": 2, "scl_done": 3, "all_done": 4}.get(step, 0)
    labels = ["① 控制箱工程", "② 架構設計", "③ SCL 生成", "④ HMI 設計"]
    cols = st.columns(4)
    for i, (col, label) in enumerate(zip(cols, labels)):
        with col:
            if i < step_num:
                st.markdown(
                    f"<div style='text-align:center;padding:10px;"
                    f"background:linear-gradient(135deg,#1b5e20,#388e3c);"
                    f"color:white;border-radius:10px;font-weight:bold;'>"
                    f"✅ {label}</div>",
                    unsafe_allow_html=True,
                )
            elif i == step_num and step != "all_done":
                st.markdown(
                    f"<div style='text-align:center;padding:10px;"
                    f"background:linear-gradient(135deg,#e65100,#ff6d00);"
                    f"color:white;border-radius:10px;font-weight:bold;'>"
                    f"👁️ {label} — 審核中</div>",
                    unsafe_allow_html=True,
                )
            else:
                st.markdown(
                    f"<div style='text-align:center;padding:10px;"
                    f"background:#424242;color:#888;border-radius:10px;'>"
                    f"⬜ {label}</div>",
                    unsafe_allow_html=True,
                )


# ==========================================
#  狀態 1：idle — 需求輸入
# ==========================================
def _render_idle(client, collection):
    app_mode = st.radio(
        "選擇作業模式：",
        ["✨ 全新專案生成 (New Project)", "🏛️ 祖傳代碼逆向重構 (Legacy Refactoring)"],
        horizontal=True,
        label_visibility="collapsed"
    )
    st.divider()

    if app_mode == "✨ 全新專案生成 (New Project)":
        # ---- 快捷範本 ----
        st.caption("💡 不知道怎麼開始？點擊下方快捷範本自動填入：")
        t1, t2, t3 = st.columns(3)
        if t1.button("🟢 簡易輸送帶邏輯", use_container_width=True):
            st.session_state.pipeline_input_area = (
                "設計一個帶有啟動停按鈕與馬達的簡單輸送帶系統。"
                "條件：要有綠色運轉燈，還要能按急停按鈕讓整台機器瞬間停下來。預算不高，越簡單越好。"
            )
        if t2.button("🌡️ PID 恆溫水槽控制", use_container_width=True):
            st.session_state.pipeline_input_area = (
                "這是一個水循環加熱系統，請幫我設計一個 PID_Compact 溫控邏輯。"
                "輸入是 PT100 溫度計，輸出是 PWM 加熱棒控制，並包含上下限警報。"
            )
        if t3.button("⚙️ 汽缸順序位移控制", use_container_width=True):
            st.session_state.pipeline_input_area = (
                "幫我寫一個順序控制邏輯 (Sequence Control)。按下啟動後，A汽缸伸出 -> "
                "A到位後B汽缸伸出 -> B到位後A退回 -> A退回到位後B退回。需要防呆與時間監控。"
            )

        # ---- 主輸入區 ----
        user_input = st.text_area(
            "請描述您的控制需求：",
            height=140,
            placeholder="或者您也可以直接在這裡打字，描述你想要達到的成果...",
            key="pipeline_input_area",
        )

        # ---- 附加檔案 & 版本 ----
        col1, col2, col3 = st.columns([2, 2, 1])
        with col1:
            pdf_file = st.file_uploader("📂 上傳 PDF 題目/規格書 (選填)", type=["pdf"], key="pipeline_pdf_uploader")
        with col2:
            tag_file = st.file_uploader(
                "📊 上傳制式變數/IO表 (CSV/Excel, 選填)",
                type=["csv", "xlsx", "xls"],
                key="pipeline_tag_uploader",
            )
        with col3:
            target_version = st.selectbox(
                "🎯 目標 TIA 版本", ["V17", "V18", "V19"], index=0, key="pipeline_target_version_sel"
            )

        # ---- TIA 部署設定 ----
        _render_tia_settings("_idle")

        # ---- 雙模式啟動按鈕 ----
        btn1, btn2 = st.columns(2)
        with btn1:
            start_step = st.button("🔍 逐步審核模式 (推薦)", type="primary", use_container_width=True)
        with btn2:
            start_auto = st.button("⚡ 全自動模式 (跳過審核)", use_container_width=True)

        if start_step or start_auto:
            if not user_input.strip() and not pdf_file and not tag_file:
                st.warning("請至少輸入需求或上傳檔案！")
                return

            # 前處理
            pdf_bytes = pdf_file.getvalue() if pdf_file else None
            tag_table_str = None
            if tag_file:
                try:
                    if tag_file.name.endswith(".csv"):
                        df_tags = pd.read_csv(tag_file)
                    else:
                        df_tags = pd.read_excel(tag_file)
                    tag_table_str = df_tags.to_markdown(index=False)
                except Exception as e:
                    st.error(f"無法讀取變數表檔案: {e}")
                    return

            # ===== 🛡️ 輸入守衛：安全分類過濾 =====
            with st.spinner("🛡️ 正在分析您的需求合法性與技術可行性..."):
                guard = validate_input(client, user_input)

            if guard.verdict == "INJECTION":
                st.error(
                    "🚨 **偵測到提示詞注入攻擊，請求已被拒絕。**\n\n"
                    f"🔍 原因：{guard.reason}\n\n"
                    "Smart PLC Studio 是一個專注於工業自動化的平台，"
                    "如有正當的 PLC/SCL 設計需求，歡迎重新描述您的自動化控制需求。"
                )
                return
            elif guard.verdict == "OFF_TOPIC":
                st.warning(
                    "⚠️ **無法處理此需求，請描述工業自動化相關的控制邏輯。**\n\n"
                    f"🔍 說明：{guard.reason}\n\n"
                    "**系統支援的需求類型範例：**\n"
                    "- 🟢 馬達啟動/停止邏輯（含急停與運轉燈）\n"
                    "- 🌡️ PID 溫度控制（PT100 + 加熱棒）\n"
                    "- ⚙️ 氣缸順序控制（A/B 缸伸出退回時序）"
                )
                return
            elif guard.verdict == "INFEASIBLE":
                # 暫存流程參數與守衛結果，顯示警告卡（透過 session_state 保持跨 rerun）
                st.session_state.guard_infeasible_pending = guard
                st.session_state.guard_infeasible_pipeline = {
                    "user_input": user_input,
                    "pdf_bytes": pdf_bytes,
                    "tag_table_str": tag_table_str,
                    "target_version": target_version,
                    "start_auto": start_auto,
                }
                st.rerun()
                return
            # ============================================

            _launch_pipeline(client, collection, user_input, pdf_bytes, tag_table_str, target_version, start_auto)
                    
    else:
        # ==========================================
        # 🏛️ 祖傳代碼逆向重構 (Legacy Refactoring)
        # ==========================================
        st.markdown("### 🏛️ 逆向考古實驗室")
        st.caption("從本機的 TIA Portal 中抽取充滿 M 點與無註解的義大利麵條邏輯，由 AI 解析其物理意義並重構為現代化程式碼。")
        
        c_proj, c_plc = st.columns([3, 1])
        legacy_proj = c_proj.text_input("📁 TIA 專案路徑 (.ap17)", value=r"C:\Users\cangk\Documents\Automation\LegacyProject.ap17")
        legacy_plc = c_plc.text_input("💻 PLC 名稱", value="PLC_1")
        
        from services.tia_extractor import TIAExtractor
        extractor = TIAExtractor()
        
        if "legacy_blocks" not in st.session_state:
            st.session_state.legacy_blocks = []
            
        if st.button("🔎 連接 TIA 提取區塊清單 (Openness)"):
            with st.spinner("正在呼叫 ExportSCL.exe 掃描專案區塊..."):
                try:
                    st.session_state.legacy_blocks = extractor.get_block_list(legacy_proj, legacy_plc)
                except Exception as e:
                    st.error(f"提取區塊清單失敗: {e}")
                    
        if st.session_state.legacy_blocks:
            st.success(f"成功掃描到 {len(st.session_state.legacy_blocks)} 個區塊！")
            target_block = st.selectbox("請選擇要重構的區塊：", st.session_state.legacy_blocks)
            
            if st.button("🔨 啟動考古學家分析與重構", type="primary"):
                from agents import mod_archaeologist
                with st.status(f"🏛️ 正在解析 {target_block} 的歷史遺跡...", expanded=True) as status:
                    try:
                        st.write("1. 匯出區塊原始 XML 邏輯...")
                        xml_content = extractor.extract_block_xml(legacy_proj, legacy_plc, target_block)
                        
                        st.write("2. AI 語義推理與結構重建...")
                        arch_res = mod_archaeologist.reverse_engineer_block(client, xml_content)
                        
                        st.session_state.pipeline_res = {"archaeologist": arch_res, "target_block": target_block}
                        st.session_state.pipeline_step = "archaeologist_done"
                        status.update(label="✅ 重構完成", state="complete", expanded=False)
                        st.rerun()
                    except Exception as e:
                        status.update(label=f"❌ 考古任務中途失敗: {e}", state="error")

# ==========================================
#  輔助：統一啟動生產線
# ==========================================
def _launch_pipeline(client, collection, user_input, pdf_bytes, tag_table_str, target_version, start_auto):
    """抽取成獨立函式，讓正常流程與 INFEASIBLE 強制繼續都能共用。"""
    st.session_state.pipeline_target_ver = target_version

    if start_auto:
        with st.spinner("全自動流水線運作中，請稍候..."):
            res = run_automated_pipeline(
                client, collection, user_input,
                pdf_bytes=pdf_bytes, tag_table_str=tag_table_str,
                target_version=target_version,
            )
        if not res:
            st.error("❌ 流水線在中途發生嚴重錯誤。")
        else:
            st.session_state.pipeline_res = res
            st.session_state.pipeline_step = "all_done"
            st.rerun()
    else:
        pipeline_input = prepare_pipeline_input(
            client, collection, user_input, pdf_bytes, tag_table_str
        )
        st.session_state.pipeline_input = pipeline_input
        try:
            panel_res = run_step_panel_engineering(client, pipeline_input)
            st.session_state.pipeline_res = {"panel": panel_res}
            st.session_state.pipeline_step = "panel_done"
            st.rerun()
        except Exception as e:
            st.error(f"❌ 控制箱工程規劃失敗: {e}")


# ==========================================
#  狀態 1.5：panel_done — 控制箱審核
# ==========================================
def _render_panel_review(client, collection):
    from agents.mod_panel_engineer import export_bom_to_excel
    # 確保匯入需要的 run_step_architecture 與 _reset_pipeline
    from workflows.orchestrator import run_step_architecture
    
    pipeline_res = st.session_state.pipeline_res
    panel_res = pipeline_res.get("panel")

    if not panel_res:
        st.error("控制箱工程規劃結果遺失，請重新開始。")
        return

    st.markdown("### 🛠️ 資深控制箱工程師分析報告")

    col1, col2 = st.columns(2)
    with col1:
        st.markdown("#### 1️⃣ 硬體選型")
        st.info("✅ **PLC 核心單元**\n\n" + panel_res.plc_selection)
        st.success("✅ **HMI 觸控面板**\n\n" + panel_res.hmi_selection)
    with col2:
        st.markdown("#### 2️⃣ 控制箱規格與配線注意事項")
        st.warning(panel_res.panel_spec + "\n\n**配線須知：**\n" + panel_res.wiring_notes)

    st.markdown("#### 3️⃣ 控制箱元件 BOM 表")
    bom_md = "| 分類 | 元件名稱 | 型號/料號 | 數量 | 單位 | 備註 |\n|---|---|---|---|---|---|\n"
    for item in panel_res.bom_items:
        bom_md += f"| {item.category} | {item.part_name} | {item.model_number} | {item.quantity} | {item.unit} | {item.remark} |\n"
    st.markdown(bom_md)
    
    try:
        excel_data = export_bom_to_excel(panel_res.bom_items)
        st.download_button(
            label="📥 下載 Excel BOM 表 (採購用)",
            data=excel_data,
            file_name="Smart_PLC_BOM.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            type="primary"
        )
    except Exception as e:
        st.error(f"Excel BOM 生成失敗: {e}")

    st.markdown("#### 4️⃣ ASCII 盤面線框圖預覽")
    st.markdown(f"<pre>{panel_res.panel_wireframe}</pre>", unsafe_allow_html=True)

    # ---- 審核控制區 ----
    st.divider()
    st.markdown("### 💬 人類工程師審核區")
    st.caption("💡 可以在下方給予回饋，例如要求變更線槽尺寸或增加某個繼電器。")

    feedback = st.text_area(
        "輸入您的修改意見或補充指示 (選填)：",
        height=100,
        placeholder="例如：請將指示燈改為 24V 的規格，再加兩個 10A 的無熔絲開關...",
        key="feedback_panel",
    )

    c1, c2, c3 = st.columns(3)
    approve = c1.button("✅ 核准，進入[架構與 I/O 配置]", type="primary", use_container_width=True, key="approve_panel")
    revise = c2.button("🔄 根據意見重新生成", use_container_width=True, key="revise_panel")
    reset = c3.button("🔙 重置流水線", use_container_width=True, key="reset_panel")

    if approve:
        try:
            arch_res = run_step_architecture(
                client, st.session_state.pipeline_input,
                feedback="【前期控制箱規劃已完成，請務必按照選定的 PLC 型號進行後續的 I/O 配置規劃】"
            )
            st.session_state.pipeline_res["arch"] = arch_res
            st.session_state.pipeline_step = "arch_done"
            st.rerun()
        except Exception as e:
            st.error(f"❌ 架構規劃失敗: {e}")
    elif revise:
        if not feedback.strip():
            st.warning("請先輸入修改意見再點擊重新生成！")
        else:
            try:
                from workflows.orchestrator import run_step_panel_engineering
                panel_res_new = run_step_panel_engineering(
                    client, st.session_state.pipeline_input, feedback=feedback
                )
                st.session_state.pipeline_res["panel"] = panel_res_new
                st.rerun()
            except Exception as e:
                st.error(f"❌ 控制箱工程規劃修改失敗: {e}")
    elif reset:
        _reset_pipeline()

# ==========================================
#  狀態 2：arch_done — 架構審核
# ==========================================
def _render_arch_review(client, collection):
    pipeline_res = st.session_state.pipeline_res
    arch_res = pipeline_res.get("arch")

    if not arch_res:
        st.error("架構結果遺失，請重新開始。")
        return

    st.markdown("### 🧠 首席架構師分析報告")

    st.markdown("#### 1️⃣ 系統需求分析")
    st.info(arch_res.req_analysis.replace('. ', '。\n\n').replace('。 ', '。\n\n'))

    st.markdown("#### 2️⃣ 硬體架構與選型")
    st.success(arch_res.hardware_selection.replace('. ', '。\n\n').replace('。 ', '。\n\n'))

    if hasattr(arch_res, 'plc_catalog_selection') and arch_res.plc_catalog_selection:
        st.markdown("#### 🎯 AI 架構師自動選型結果")
        st.warning(f"根據需求分析，架構設計師推薦使用：**{arch_res.plc_catalog_selection}**")

    st.markdown("#### 3️⃣ I/O 點位配置清單")
    st.markdown(re.sub(r"\|\s*\|", "|\n|", arch_res.io_allocation))

    # ---- 審核控制區 ----
    st.divider()
    st.markdown("### 💬 人類工程師審核區")
    st.caption("💡 即使不按任何按鈕，您的進度也會自動保存。可以隨時關閉頁面稍後回來。")

    feedback = st.text_area(
        "輸入您的修改意見或補充指示 (選填)：",
        height=100,
        placeholder="例如：我覺得應該改用 S7-1500，另外少了一個急停按鈕的 I/O 點位...",
        key="feedback_arch",
    )

    c1, c2, c3 = st.columns(3)
    approve = c1.button("✅ 核准，進入下一步", type="primary", use_container_width=True, key="approve_arch")
    revise = c2.button("🔄 根據意見重新生成", use_container_width=True, key="revise_arch")
    reset = c3.button("🔙 重置流水線", use_container_width=True, key="reset_arch")

    if approve:
        try:
            scl_res, clean_scl, review_result, safety_result = run_step_scl(
                client, collection,
                st.session_state.pipeline_input, arch_res,
                st.session_state.pipeline_target_ver,
            )
            st.session_state.pipeline_res["code_review"] = review_result
            st.session_state.pipeline_res["safety_audit"] = safety_result
            st.session_state.pipeline_res["scl"] = {"res": scl_res, "clean_scl": clean_scl}
            st.session_state.pipeline_step = "scl_done"
            st.rerun()
        except Exception as e:
            st.error(f"❌ SCL 生成失敗: {e}")
    elif revise:
        if not feedback.strip():
            st.warning("請先輸入修改意見再點擊重新生成！")
        else:
            try:
                arch_res_new = run_step_architecture(
                    client, st.session_state.pipeline_input, feedback=feedback
                )
                st.session_state.pipeline_res["arch"] = arch_res_new
                st.rerun()
            except Exception as e:
                st.error(f"❌ 架構重新生成失敗: {e}")
    elif reset:
        _reset_pipeline()


# ==========================================
#  狀態 3：scl_done — SCL 審核
# ==========================================
def _render_scl_review(client, collection):
    pipeline_res = st.session_state.pipeline_res
    arch_res = pipeline_res.get("arch")
    scl_data = pipeline_res.get("scl")

    # ---- 已核准的架構 (摺疊) ----
    with st.expander("📋 架構設計結果 (已核准 ✅)", expanded=False):
        if arch_res:
            st.info(arch_res.req_analysis.replace('. ', '。\n\n').replace('。 ', '。\n\n'))
            st.success(arch_res.hardware_selection.replace('. ', '。\n\n').replace('。 ', '。\n\n'))
            if hasattr(arch_res, 'plc_catalog_selection') and arch_res.plc_catalog_selection:
                st.warning(f"AI 選型：**{arch_res.plc_catalog_selection}**")
            st.markdown(re.sub(r"\|\s*\|", "|\n|", arch_res.io_allocation))

    # ---- SCL 結果 ----
    st.markdown("### 💻 SCL 程式碼審核")
    if scl_data:
        st.info(f"**🧠 邏輯思路解析：**\n{scl_data['res'].thinking}")
        st.success(f"**💡 新手註解與教學：**\n{scl_data['res'].tutorial}")

        st.divider()
        st.markdown("#### 💻 可匯入 TIA 的原始程式碼")
        st.code(scl_data['clean_scl'], language="pascal")

        # 變數表預覽
        try:
            df = pd.read_csv(
                io.StringIO(scl_data['res'].csv_tags),
                dtype=str, skipinitialspace=True, on_bad_lines='skip',
            )
            df = df.fillna("")
            st.markdown("#### 📊 TIA 全域變數預覽")
            st.markdown(f'<div style="overflow-x:auto; width:100%;">{df.to_html(index=False, border=0)}</div>', unsafe_allow_html=True)
        except Exception:
            pass

        # 1. 代碼審查分數
        review = pipeline_res.get("code_review", {})
        if review:
            score = review.get("score", "N/A")
            fb = review.get("feedback", "")
            if isinstance(score, int) and score < 70:
                st.warning(f"⚠️ 代碼審查得分：{score}/100 — {fb}")
            else:
                st.success(f"✅ 代碼審查得分：{score}/100 — {fb}")

        # 2. 工安稽核報告 (重點呈現)
        safety = pipeline_res.get("safety_audit")
        if safety:
            st.markdown("---")
            st.markdown("#### 🛡️ 工安稽核報告")
            with st.container():
                s_score = safety.safety_score
                if s_score >= 80:
                    st.success(f"🛡️ **安全等級：高 ({s_score}/100)**")
                elif s_score >= 60:
                    st.warning(f"🛡️ **安全等級：中 ({s_score}/100)**")
                else:
                    st.error(f"🚨 **安全等級：低 ({s_score}/100) — 偵測到嚴重隱患！**")

                col_a, col_b = st.columns(2)
                with col_a:
                    st.markdown("**❌ 偵測到的風險：**")
                    if safety.critical_risks:
                        for risk in safety.critical_risks:
                            st.write(f"- {risk}")
                    else:
                        st.write("- 未偵測到明顯風險")
                with col_b:
                    st.markdown("**✅ 已具備的安全機制：**")
                    if safety.safety_features_found:
                        for feat in safety.safety_features_found:
                            st.write(f"- {feat}")
                    else:
                        st.write("- 未偵測到明確安全機制")

                if safety.recommendations:
                    st.info(f"💡 **稽核員建議：**\n{safety.recommendations}")
    else:
        st.error("SCL 結果遺失。")

    # ---- 審核控制區 ----
    st.divider()
    st.markdown("### 💬 人類工程師審核區")
    st.caption("💡 即使不按任何按鈕，您的進度也會自動保存。可以隨時關閉頁面稍後回來。")

    feedback = st.text_area(
        "輸入您的修改意見或補充指示 (選填)：",
        height=100,
        placeholder="例如：Timer 應該用 TON 而不是 TOF，請把超時時間改為 5 秒...",
        key="feedback_scl",
    )

    c1, c2, c3 = st.columns(3)
    approve = c1.button("✅ 核准，進入下一步", type="primary", use_container_width=True, key="approve_scl")
    revise = c2.button("🔄 根據意見重新生成", use_container_width=True, key="revise_scl")
    reset = c3.button("🔙 重置流水線", use_container_width=True, key="reset_scl")

    if approve:
        # Step 3: HMI (非致命)
        try:
            hmi_res = run_step_hmi(client, st.session_state.pipeline_input, arch_res)
            st.session_state.pipeline_res["hmi"] = hmi_res
        except Exception as e:
            st.warning(f"⚠️ HMI 規劃失敗 (非致命): {e}")
        st.session_state.pipeline_step = "all_done"
        st.rerun()
    elif revise:
        if not feedback.strip():
            st.warning("請先輸入修改意見再點擊重新生成！")
        else:
            try:
                scl_res, clean_scl, review_result, safety_result = run_step_scl(
                    client, collection,
                    st.session_state.pipeline_input, arch_res,
                    st.session_state.pipeline_target_ver,
                    feedback=feedback,
                )
                st.session_state.pipeline_res["code_review"] = review_result
                st.session_state.pipeline_res["safety_audit"] = safety_result
                st.session_state.pipeline_res["scl"] = {"res": scl_res, "clean_scl": clean_scl}
                st.rerun()
            except Exception as e:
                st.error(f"❌ SCL 重新生成失敗: {e}")
    elif reset:
        _reset_pipeline()


# ==========================================
#  狀態 3.5：archaeologist_done — 考古重構結果
# ==========================================
def _render_archaeologist_review(client, collection):
    res = st.session_state.pipeline_res
    arch_res = res.get("archaeologist")
    target_block = res.get("target_block", "Unknown Block")
    
    st.markdown(f"### 🏛️ {target_block} 考古重構結果")
    st.success("✅ 舊有邏輯已成功進行語義推導與結構現代化！")
    
    if arch_res:
        st.info(f"**🧠 語義推導與重構思路：**\n{arch_res.thinking}")
        
        c1, c2 = st.columns(2)
        with c1:
            st.markdown("#### 📜 重構後的現代化 SCL 程式碼")
            st.code(arch_res.refactored_scl, language="pascal")
            
        with c2:
            st.markdown("#### 🏷️ 整理後的新變數表推薦")
            try:
                import io, pandas as pd
                df = pd.read_csv(
                    io.StringIO(arch_res.new_tag_table),
                    dtype=str, skipinitialspace=True, on_bad_lines='skip',
                )
                df = df.fillna("")
                st.markdown(f'<div style="overflow-x:auto; width:100%;">{df.to_html(index=False, border=0)}</div>', unsafe_allow_html=True)
            except Exception:
                st.code(arch_res.new_tag_table)
    
    st.divider()
    if st.button("🔙 返回首頁", use_container_width=True):
        _reset_pipeline()

# ==========================================
#  狀態 4：all_done — 最終結果展示 + 部署
# ==========================================
def _render_all_done(client, collection):
    pipeline_res = st.session_state.pipeline_res
    target_version = st.session_state.pipeline_target_ver

    st.success("🎉 全部生成完畢！")

    # ============================================================
    #  🚀 TIA 部署區 — 置頂醒目位置
    # ============================================================
    if "scl" in pipeline_res:
        st.markdown("---")
        st.markdown("### 🚀 部署至真實環境 (TIA Portal Openness)")

        _render_tia_settings("_deploy")

        is_create_mode = (st.session_state.global_tia_mode == "✨ 從無到有全新生成")
        tia_plc = st.session_state.global_tia_plc
        target_identifier = (
            st.session_state.global_tia_proj if not is_create_mode
            else os.path.join(st.session_state.global_tia_dir, st.session_state.global_tia_new_name)
        )

        msg_target = f"👉 **目標路徑**： `{target_identifier}`"
        msg_plc = f"👉 **設備名稱**： `{tia_plc}`"
        if is_create_mode and pipeline_res.get("arch"):
            ai_selected_model = pipeline_res["arch"].plc_catalog_selection
            msg_plc += f"\n\n👉 **AI 自動選型**： `{ai_selected_model}`"
        st.info(f"{msg_target}\n\n{msg_plc}")

        scl_data = pipeline_res["scl"]
        
        btn_col, chaos_col = st.columns(2)
        with btn_col:
            if st.button("⚡ 一鍵自動寫入 TIA Portal", type="primary", use_container_width=True, key="tia_export_btn"):
                _execute_tia_deploy(pipeline_res, scl_data, is_create_mode, tia_plc)
        with chaos_col:
            if st.button("🧨 啟動 Chaos Agent (需已開啟 PLCSIM)", use_container_width=True, key="chaos_test_btn"):
                try:
                    plan, logs = run_step_chaos_testing(client, scl_data['clean_scl'], scl_data['res'].csv_tags)
                    st.session_state.pipeline_res["chaos"] = {"plan": plan, "logs": logs}
                    st.session_state.pipeline_active_tab = "🧨 混沌壓力測試報告"
                    st.rerun()
                except Exception as e:
                    st.error(f"❌ 混沌測試執行失敗: {e}")

        # 下載按鈕也放在這裡讓部署區更完整
        dcol1, dcol2 = st.columns(2)
        with dcol1:
            st.download_button(
                label="📥 下載 SCL 原始碼 (.scl)",
                data=scl_data['clean_scl'].encode('utf-8-sig'),
                file_name=f"Automated_Block_{target_version}.scl",
                mime="text/plain",
                use_container_width=True,
                key="dl_scl_btn",
            )
        with dcol2:
            try:
                df_dl = pd.read_csv(
                    io.StringIO(scl_data['res'].csv_tags),
                    dtype=str, skipinitialspace=True, on_bad_lines='skip',
                )
                if df_dl.empty:
                    df_dl = pd.DataFrame([{"Name": "ParserError", "Comment": "Could not parse AI output correctly."}])
                else:
                    df_dl = df_dl.fillna("")
                excel_buf = io.BytesIO()
                with pd.ExcelWriter(excel_buf, engine='openpyxl') as writer:
                    df_dl.to_excel(writer, index=False, sheet_name="PLC Tags")
                st.download_button(
                    label="📥 下載 TIA 變數表 (.xlsx)",
                    data=excel_buf.getvalue(),
                    file_name=f"PLC_Tags_{target_version}.xlsx",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    use_container_width=True,
                    key="dl_tags_btn",
                )
            except Exception as e:
                st.error(f"變數表封裝失敗: {e}")

    st.divider()

    # ============================================================
    #  操作列：重新開始
    # ============================================================
    if st.button("🔙 重新開始一個新專案", use_container_width=True, key="reset_final"):
        _reset_pipeline()

    # ============================================================
    #  詳細結果頁籤
    # ============================================================
    st.markdown("#### 📑 詳細生成報告")
    if "pipeline_active_tab" not in st.session_state:
        st.session_state.pipeline_active_tab = "📋 系統硬體與架構配置"

    tab_selection = st.radio(
        "選擇頁籤：",
        ["📋 系統硬體與架構配置", "💻 核心邏輯與 SCL 程式碼", "🖥️ HMI 人機介面佈局", "🧨 混沌壓力測試報告", "📘 系統技術維護手冊"],
        horizontal=True,
        label_visibility="collapsed",
        key="pipeline_active_tab",
    )
    st.divider()

    # --------- Tab 1: 架構 ---------
    if tab_selection == "📋 系統硬體與架構配置":
        if pipeline_res.get("arch"):
            st.markdown("### 🧠 首席架構師分析報告")
            st.info(pipeline_res["arch"].req_analysis.replace('. ', '。\n\n').replace('。 ', '。\n\n'))
            st.success(pipeline_res["arch"].hardware_selection.replace('. ', '。\n\n').replace('。 ', '。\n\n'))

            if hasattr(pipeline_res["arch"], 'plc_catalog_selection') and pipeline_res["arch"].plc_catalog_selection:
                st.markdown("#### 🎯 AI 架構師自動選型結果")
                st.warning(f"根據需求分析，架構設計師推薦使用：**{pipeline_res['arch'].plc_catalog_selection}**")

            st.divider()
            st.markdown("#### ⚙️ I/O 點位配置清單")
            st.markdown(re.sub(r"\|\s*\|", "|\n|", pipeline_res["arch"].io_allocation))
        else:
            st.warning("架構分析遺失。")

    # --------- Tab 2: SCL ---------
    elif tab_selection == "💻 核心邏輯與 SCL 程式碼":
        if "scl" in pipeline_res:
            scl_data = pipeline_res["scl"]
            st.markdown("### 🎓 程式導師代碼解析")
            st.info(f"**🧠 邏輯思路解析：**\n{scl_data['res'].thinking}")
            st.success(f"**💡 新手註解與教學：**\n{scl_data['res'].tutorial}")

            st.divider()
            st.markdown("#### 💻 可匯入 TIA 的原始程式碼")
            st.code(scl_data['clean_scl'], language="pascal")

            st.markdown("#### 📊 TIA 全域變數預覽")
            try:
                df = pd.read_csv(
                    io.StringIO(scl_data['res'].csv_tags),
                    dtype=str, skipinitialspace=True, on_bad_lines='skip',
                )
                df = df.fillna("")
                st.markdown(f'<div style="overflow-x:auto; width:100%;">{df.to_html(index=False, border=0)}</div>', unsafe_allow_html=True)
            except Exception:
                pass
        else:
            st.warning("程式碼生成失敗或遺失。")

    # --------- Tab 3: HMI ---------
    elif tab_selection == "🖥️ HMI 人機介面佈局":
        if "hmi" in pipeline_res:
            st.markdown("### 🎨 介面規劃師草圖")
            st.markdown("#### UI/UX 與變數對應表")
            st.info(pipeline_res["hmi"].tag_mapping)
            st.divider()
            st.markdown("#### 📐 ASCII 線框佈局圖 (Wireframe)")
            st.code(pipeline_res["hmi"].wireframe, language="text")
        else:
            st.info("本次生成無 HMI 結果。")

    # --------- Tab 4: Chaos ---------
    elif tab_selection == "🧨 混沌壓力測試報告":
        if "chaos" in pipeline_res:
            chaos_data = pipeline_res["chaos"]
            plan = chaos_data["plan"]
            
            st.markdown("### 🧨 Chaos Agent 壓力測試最終報告")
            st.info(f"**🧠 攻擊劇本規劃思路：**\n{plan.thinking}")
            
            with st.expander("🛠️ 查看生成的破壞任務", expanded=False):
                for act in plan.chaos_actions:
                    st.markdown(f"- **{act.action_type.upper()}**: 目標 `{act.target_tags}` => {act.description}")
            
            st.divider()
            st.markdown("#### 📜 執行日誌與崩潰偵測結果")
            log_text = "\n".join(chaos_data["logs"])
            if "🚨" in log_text:
                st.error("系統在壓力測試中發生安全崩潰！請檢查以下日誌。")
            else:
                st.success("✅ 系統成功通過所有非法時序與衝突攻擊，未發生崩潰！")
            
            st.code(log_text, language="text")
        else:
            st.info("⚠️ 尚未執行混沌壓力測試。請在上方點擊「啟動 Chaos Agent」。")

    # --------- Tab 5: Tech Writer ---------
    elif tab_selection == "📘 系統技術維護手冊":
        if "tech_manual" not in pipeline_res:
            st.info("系統維護手冊尚未編纂，請點擊下方按鈕根據目前所有設計結果自動生成！")
            if st.button("📝 啟動寫手自動編纂 (需約 15~30 秒)", type="primary"):
                try:
                    manual_res = run_step_tech_writer(client, pipeline_res)
                    st.session_state.pipeline_res["tech_manual"] = manual_res
                    st.rerun()
                except Exception as e:
                    st.error(f"編纂手冊失敗: {e}")
        else:
            manual = pipeline_res["tech_manual"]
            st.markdown("### 📘 ISO/IEC 系統技術維護手冊")
            st.info(f"**🧠 寫手編纂思路：**\n{manual.thinking}")
            
            # 給手冊下載連結
            col_b, _ = st.columns([1, 2])
            with col_b:
                st.download_button(
                    label="📥 將手冊下載為 Markdown (.md) 歸檔",
                    data=manual.markdown_manual.encode('utf-8'),
                    file_name="System_Maintenance_Manual.md",
                    mime="text/markdown",
                    use_container_width=True
                )
            
            st.divider()
            
            # Mermaid Chart Preview
            if manual.mermaid_chart:
                with st.expander("📊 SCL 控制邏輯流程圖預覽 (Mermaid)", expanded=True):
                    # Wrap the raw mermaid chart code in a st.markdown block if they used backticks, or prepend them
                    mermaid_code = manual.mermaid_chart.strip()
                    if not mermaid_code.startswith("```"):
                        mermaid_code = f"```mermaid\n{mermaid_code}\n```"
                    st.markdown(mermaid_code)
                    
            st.divider()
            st.markdown(manual.markdown_manual)


# ==========================================
#  TIA Portal 設定 (共用元件)
# ==========================================
def _render_tia_settings(key_suffix=""):
    """渲染 TIA Portal 部署設定 (可多處複用，用 key_suffix 區分)"""
    with st.expander("🛠️ TIA Portal 自動部署設定"):
        modes = ["🔄 更新本機既有專案", "✨ 從無到有全新生成"]
        current_idx = modes.index(st.session_state.global_tia_mode) if st.session_state.global_tia_mode in modes else 0
        selected_mode = st.radio(
            "部署模式", modes, index=current_idx, horizontal=True,
            key=f"tia_mode_radio{key_suffix}",
        )
        st.session_state.global_tia_mode = selected_mode
        st.divider()

        if selected_mode == "🔄 更新本機既有專案":
            col_p, col_b = st.columns([5, 1])
            with col_p:
                proj = st.text_input(
                    "📁 TIA 專案本機路徑 (.ap17)",
                    value=st.session_state.global_tia_proj,
                )
                if proj != st.session_state.global_tia_proj:
                    st.session_state.global_tia_proj = proj
                    st.rerun()

            with col_b:
                st.markdown("<div style='margin-top:27px;'></div>", unsafe_allow_html=True)
                if st.button("📂 瀏覽..", use_container_width=True, key=f"btn_browse_proj{key_suffix}"):
                    _browse_file()

            plc = st.text_input(
                "💻 目標 PLC 設備名稱",
                value=st.session_state.global_tia_plc,
            )
            if plc != st.session_state.global_tia_plc:
                st.session_state.global_tia_plc = plc
                st.rerun()
        else:
            col_d, col_b = st.columns([5, 1])
            with col_d:
                d = st.text_input(
                    "📁 目標存放資料夾",
                    value=st.session_state.global_tia_dir,
                )
                if d != st.session_state.global_tia_dir:
                    st.session_state.global_tia_dir = d
                    st.rerun()
            with col_b:
                st.markdown("<div style='margin-top:27px;'></div>", unsafe_allow_html=True)
                if st.button("📂 瀏覽..", use_container_width=True, key=f"btn_browse_dir{key_suffix}"):
                    _browse_dir()

            c1, c2 = st.columns(2)
            with c1:
                nn = st.text_input(
                    "📝 新專案名稱",
                    value=st.session_state.global_tia_new_name,
                )
                if nn != st.session_state.global_tia_new_name:
                    st.session_state.global_tia_new_name = nn
                    st.rerun()
            with c2:
                plc = st.text_input(
                    "💻 新 PLC 設備名稱",
                    value=st.session_state.global_tia_plc,
                )
                if plc != st.session_state.global_tia_plc:
                    st.session_state.global_tia_plc = plc
                    st.rerun()

            st.info("💡 PLC 硬體型號將由 AI 架構設計師根據您的需求自動選定。")


def _browse_file():
    """使用 tkinter 對話框選擇 .ap17 檔案"""
    try:
        import tkinter as tk
        from tkinter import filedialog
        root = tk.Tk()
        root.withdraw()
        root.attributes('-topmost', True)
        fp = filedialog.askopenfilename(filetypes=[("TIA Project", "*.ap17")])
        root.destroy()
        if fp:
            st.session_state.global_tia_proj = fp.replace('/', '\\')
            st.rerun()
    except Exception as e:
        import traceback
        traceback.print_exc()


def _browse_dir():
    """使用 tkinter 對話框選擇資料夾"""
    try:
        import tkinter as tk
        from tkinter import filedialog
        root = tk.Tk()
        root.withdraw()
        root.attributes('-topmost', True)
        dp = filedialog.askdirectory()
        root.destroy()
        if dp:
            st.session_state.global_tia_dir = dp.replace('/', '\\')
            st.rerun()
    except Exception as e:
        import traceback
        traceback.print_exc()


# ==========================================
#  TIA 部署執行
# ==========================================
def _execute_tia_deploy(pipeline_res, scl_data, is_create_mode, tia_plc):
    """實際執行 TIA Portal Openness 寫入"""
    if not tia_plc.strip():
        st.warning("請填寫目標 PLC 名稱。")
        return
    if not is_create_mode and not st.session_state.global_tia_proj.strip():
        st.warning("請填寫完整的專案路徑。")
        return
    if is_create_mode and (not st.session_state.global_tia_dir.strip() or not st.session_state.global_tia_new_name.strip()):
        st.warning("請填寫目標存放資料夾與新專案名稱。")
        return

    with st.spinner("正在與 TIA Portal 建立通訊，並在背景執行匯入 (約需 30~60 秒)..."):
        temp_scl_path = os.path.abspath("temp_export.scl")
        temp_tags_path = os.path.abspath("temp_tags.tsv")
        try:
            clean_code = scl_data['clean_scl'].replace('\x00', '').replace('$00', '16#00')
            with open(temp_scl_path, "w", encoding="utf-8") as f:
                f.write(clean_code)

            # TSV 變數表
            try:
                df = pd.read_csv(
                    io.StringIO(scl_data['res'].csv_tags),
                    dtype=str, skipinitialspace=True, on_bad_lines='skip',
                )
                df = df.fillna("")
                if not df.empty:
                    df.to_csv(temp_tags_path, sep='\t', index=False, encoding="utf-8-sig")
            except Exception as e:
                st.warning(f"變數表匯出警告: {e}")
                temp_tags_path = None

            exporter = TIAExporter()

            if is_create_mode:
                # 從 AI 架構師選型結果查 catalog 取 OrderNumber
                _plc_catalog = {}
                try:
                    with open("data/plc_catalog.json", "r", encoding="utf-8") as _f:
                        _plc_catalog = json.load(_f)
                except Exception:
                    pass
                ai_model_key = pipeline_res["arch"].plc_catalog_selection if pipeline_res.get("arch") else ""
                mlfb_str = _plc_catalog.get(ai_model_key, "")
                if not mlfb_str:
                    st.warning(f"⚠️ AI 選擇的型號 '{ai_model_key}' 不在型錄中，將嘗試以預設方式建立。")
                res = exporter.import_scl_to_tia(
                    project_path_or_dir=st.session_state.global_tia_dir,
                    scl_path=temp_scl_path,
                    plc_name=tia_plc,
                    tag_tsv_path=temp_tags_path,
                    is_create_mode=True,
                    project_name=st.session_state.global_tia_new_name,
                    mlfb_string=mlfb_str,
                )
            else:
                res = exporter.import_scl_to_tia(
                    project_path_or_dir=st.session_state.global_tia_proj,
                    scl_path=temp_scl_path,
                    plc_name=tia_plc,
                    tag_tsv_path=temp_tags_path,
                    is_create_mode=False,
                )

            if res["success"]:
                st.success(f"🎉 {res['message']}")
                with st.expander("查看 TIA 背景執行紀錄"):
                    st.code(res['details'], language="text")
            else:
                st.error(f"❌ {res['message']}")
                if res.get('error'):
                    st.error(f"錯誤原因:\n```text\n{res['error']}\n```")
                if res.get('details'):
                    with st.expander("查看 TIA 背景執行紀錄"):
                        st.code(res['details'], language="text")
        finally:
            if os.path.exists(temp_scl_path):
                os.remove(temp_scl_path)
            if temp_tags_path and os.path.exists(temp_tags_path):
                os.remove(temp_tags_path)


# ==========================================
#  工具函式
# ==========================================
def _reset_pipeline():
    """重置流水線狀態 (保留 TIA 設定與輸入框文字)"""
    st.session_state.pipeline_step = "idle"
    st.session_state.pipeline_res = {}
    st.session_state.pipeline_input = ""
    st.rerun()
