# orchestrator_ui.py
import streamlit as st
import pandas as pd
import io
import re
import os
from workflows.orchestrator import run_automated_pipeline
from services.tia_exporter import TIAExporter

def render(client, collection):
    st.markdown("### 🧩 無縫資料流生產線")
    st.markdown("真正的自動化設計：只需輸入一次需求，AI 代理人們將依次為您設計 **[硬體架構]** ➡️ **[自動化 SCL 程式碼]** ➡️ **[工業 HMI 佈局]**！")

    # ========= 快捷範本區 (Prompt Templates) =========
    if "pipeline_input_area" not in st.session_state:
        st.session_state.pipeline_input_area = ""

    st.caption("💡 不知道怎麼開始？點擊下方快捷範本自動填入：")
    t_col1, t_col2, t_col3 = st.columns(3)
    if t_col1.button("🟢 簡易輸送帶邏輯", use_container_width=True):
         st.session_state.pipeline_input_area = "設計一個帶有啟動停按鈕與馬達的簡單輸送帶系統。條件：要有綠色運轉燈，還要能按急停按鈕讓整台機器瞬間停下來。預算不高，越簡單越好。"
    if t_col2.button("🌡️ PID 恆溫水槽控制", use_container_width=True):
         st.session_state.pipeline_input_area = "這是一個水循環加熱系統，請幫我設計一個 PID_Compact 溫控邏輯。輸入是 PT100 溫度計，輸出是 PWM 加熱棒控制，並包含上下限警報。"
    if t_col3.button("⚙️ 汽缸順序位移控制", use_container_width=True):
         st.session_state.pipeline_input_area = "幫我寫一個順序控制邏輯 (Sequence Control)。按下啟動後，A汽缸伸出 -> A到位後B汽缸伸出 -> B到位後A退回 -> A退回到位後B退回。需要防呆與時間監控。"

    # ================= 輸入區 =================
    user_input = st.text_area(
        "請描述您的控制需求：", 
        height=140, 
        placeholder="或者您也可以直接在這裡打字，描述你想要達到的成果...",
        key="pipeline_input_area"
    )
    
    # 底部選項與啟動按鈕
    col1, col2, col3 = st.columns([2, 2, 1])
    with col1:
        pdf_file = st.file_uploader("📂 上傳 PDF 題目/規格書 (選填)", type=["pdf"], key="pipeline_pdf_uploader")
    with col2:
        tag_file = st.file_uploader("📊 上傳制式變數/IO表 (CSV/Excel, 選填)", type=["csv", "xlsx", "xls"], key="pipeline_tag_uploader")
    with col3:
        target_version = st.selectbox("🎯 目標 TIA 版本", ["V17", "V18", "V19"], index=0, key="pipeline_target_version")
    
    if "global_tia_mode" not in st.session_state:
        st.session_state.global_tia_mode = "🔄 更新本機既有專案"
    if "global_tia_proj" not in st.session_state:
        st.session_state.global_tia_proj = r"C:\Users\cangk\Documents\Automation\MyTestProject.ap17"
    if "global_tia_plc" not in st.session_state:
        st.session_state.global_tia_plc = "PLC_1"
    if "global_tia_dir" not in st.session_state:
        st.session_state.global_tia_dir = r"C:\Users\cangk\Documents\Automation"
    if "global_tia_new_name" not in st.session_state:
        st.session_state.global_tia_new_name = "AutoGenerated_Project"
    if "global_tia_mlfb_key" not in st.session_state:
        st.session_state.global_tia_mlfb_key = ""

    # 載入 PLC 型錄
    import json
    catalog_path = "data/plc_catalog.json" if os.path.exists("data/plc_catalog.json") else "../data/plc_catalog.json"
    plc_catalog = {}
    try:
        with open(catalog_path, "r", encoding="utf-8") as f:
            plc_catalog = json.load(f)
    except Exception:
        plc_catalog = {"S7-1200 CPU 1215C DC/DC/DC (V4.4)": "OrderNumber:6ES7 215-1AG40-0XB0/V4.4"}

    with st.expander("🛠️ TIA Portal 自動部署設定 (提前設定，生成後可一鍵匯出)"):
        st.session_state.global_tia_mode = st.radio("部署模式", ["🔄 更新本機既有專案", "✨ 從無到有全新生成"], horizontal=True)
        st.divider()
        
        if st.session_state.global_tia_mode == "🔄 更新本機既有專案":
            col_p, col_b = st.columns([5, 1])
            with col_p:
                user_input_proj = st.text_input("📁 TIA 專案本機路徑 (.ap17)", value=st.session_state.global_tia_proj)
                if user_input_proj != st.session_state.global_tia_proj:
                    st.session_state.global_tia_proj = user_input_proj
            with col_b:
                st.markdown("<div style='margin-top: 27px;'></div>", unsafe_allow_html=True)
                if st.button("📂 瀏覽..", use_container_width=True, key="btn_browse_proj"):
                    import tkinter as tk
                    from tkinter import filedialog
                    root = tk.Tk()
                    root.withdraw()
                    root.attributes('-topmost', True)
                    filepath = filedialog.askopenfilename(filetypes=[("TIA Project", "*.ap17")])
                    root.destroy()
                    if filepath:
                        st.session_state.global_tia_proj = filepath.replace('/', '\\')
                        st.rerun()

            user_input_plc = st.text_input("💻 目標 PLC 設備名稱", value=st.session_state.global_tia_plc)
            if user_input_plc != st.session_state.global_tia_plc:
                st.session_state.global_tia_plc = user_input_plc
                
        else:
            col_d, col_b = st.columns([5, 1])
            with col_d:
                user_input_dir = st.text_input("📁 目標存放資料夾", value=st.session_state.global_tia_dir)
                if user_input_dir != st.session_state.global_tia_dir:
                    st.session_state.global_tia_dir = user_input_dir
            with col_b:
                st.markdown("<div style='margin-top: 27px;'></div>", unsafe_allow_html=True)
                if st.button("📂 瀏覽..", use_container_width=True, key="btn_browse_dir"):
                    import tkinter as tk
                    from tkinter import filedialog
                    root = tk.Tk()
                    root.withdraw()
                    root.attributes('-topmost', True)
                    dirpath = filedialog.askdirectory()
                    root.destroy()
                    if dirpath:
                        st.session_state.global_tia_dir = dirpath.replace('/', '\\')
                        st.rerun()
            
            c1, c2 = st.columns(2)
            with c1:
                user_input_new_name = st.text_input("📝 新專案名稱", value=st.session_state.global_tia_new_name)
                if user_input_new_name != st.session_state.global_tia_new_name:
                    st.session_state.global_tia_new_name = user_input_new_name
            with c2:
                user_input_plc = st.text_input("💻 新 PLC 設備名稱", value=st.session_state.global_tia_plc)
                if user_input_plc != st.session_state.global_tia_plc:
                    st.session_state.global_tia_plc = user_input_plc
                    
            mlfb_options = list(plc_catalog.keys())
            default_index = 0
            if st.session_state.global_tia_mlfb_key in mlfb_options:
                default_index = mlfb_options.index(st.session_state.global_tia_mlfb_key)
            selected_mlfb = st.selectbox("🎯 選擇 PLC 硬體型錄", mlfb_options, index=default_index)
            st.session_state.global_tia_mlfb_key = selected_mlfb
            
    if st.button("🚀 啟動無縫資料流生產線", type="primary", use_container_width=True):
        if not user_input.strip() and not pdf_file and not tag_file:
            st.warning("請至少輸入需求或上傳檔案！")
        else:
            pdf_bytes = pdf_file.getvalue() if pdf_file else None
            
            tag_table_str = None
            if tag_file:
                try:
                    if tag_file.name.endswith(".csv"):
                        df_tags = pd.read_csv(tag_file)
                    else:
                        df_tags = pd.read_excel(tag_file)
                    tag_table_str = df_tags.to_markdown(index=False)
                except Exception as e:
                    st.error(f"無法讀取變數表檔案: {e}")
            
            # 啟動自動化流水線
            with st.spinner("流水線運作中，請稍候..."):
                pipeline_res = run_automated_pipeline(client, collection, user_input, pdf_bytes=pdf_bytes, tag_table_str=tag_table_str, target_version=target_version)
            
            if not pipeline_res:
                 st.error("❌ 流水線在中途發生嚴重錯誤。")
                 if "pipeline_res" in st.session_state:
                     del st.session_state.pipeline_res
            else:
                 st.session_state.pipeline_res = pipeline_res
                 
    # ==========================================
    # 絕美展示：當 session_state 裡面有結果時就畫出來
    # ==========================================
    if st.session_state.get("pipeline_res"):
        pipeline_res = st.session_state.pipeline_res
        
        st.success("🎉 全部生成完畢！請使用下方頁籤切換查看報告：")
        
        # 建立狀態保留的切換器 (取代會被重置的 st.tabs)
        if "pipeline_active_tab" not in st.session_state:
            st.session_state.pipeline_active_tab = "📋 系統硬體與架構配置"
            
        tab_selection = st.radio(
            "選擇頁籤：",
            ["📋 系統硬體與架構配置", "💻 核心邏輯與 SCL 程式碼", "🖥️ HMI 人機介面佈局"],
            horizontal=True,
            label_visibility="collapsed",
            key="pipeline_active_tab"
        )
        st.divider()
        
        # --------- Tab 1: 架構成果 ---------
        if tab_selection == "📋 系統硬體與架構配置":
            if pipeline_res.get("arch"):
                st.markdown("### 🧠 首席架構師分析報告")
                st.info(pipeline_res["arch"].req_analysis.replace('. ', '。\n\n').replace('。 ', '。\n\n'))
                st.success(pipeline_res["arch"].hardware_selection.replace('. ', '。\n\n').replace('。 ', '。\n\n'))
                
                st.divider()
                st.markdown("#### ⚙️ I/O 點位配置清單")
                # 處理 JSON 把表格換行吃掉的極端狀況
                io_table = re.sub(r"\|\s*\|", "|\n|", pipeline_res["arch"].io_allocation)
                st.markdown(io_table)
            else:
                st.warning("架構分析遺失。")
                
        # --------- Tab 2: SCL 成果 ---------
        elif tab_selection == "💻 核心邏輯與 SCL 程式碼":
            if "scl" in pipeline_res:
                scl_data = pipeline_res["scl"]
                st.markdown("### 🎓 程式導師代碼解析")
                st.info(f"**🧠 邏輯思路解析：**\n{scl_data['res'].thinking}")
                st.success(f"**💡 新手註解與教學：**\n{scl_data['res'].tutorial}")
                
                st.divider()
                st.markdown("#### 💻 可匯入 TIA 的原始程式碼")
                st.code(scl_data['clean_scl'], language="pascal")
                
                # 下載按鈕排版
                dcol1, dcol2 = st.columns([1, 1])
                with dcol1:
                    st.download_button(
                        label="📥 下載 SCL 外部原始碼 (.scl)", 
                        data=scl_data['clean_scl'].encode('utf-8-sig'), 
                        file_name=f"Automated_Block_{target_version}.scl", 
                        mime="text/plain",
                        use_container_width=True,
                        key="dl_scl_btn"
                    )
                with dcol2:
                    try:
                        df = pd.read_csv(io.StringIO(scl_data['res'].csv_tags), dtype=str, skipinitialspace=True, on_bad_lines='skip')
                        if df.empty:
                            df = pd.DataFrame([{"Name": "ParserError", "Comment": "Could not parse AI output correctly."}])
                        else:
                            df = df.fillna("")
                        excel_buffer = io.BytesIO()
                        with pd.ExcelWriter(excel_buffer, engine='openpyxl') as writer: 
                            df.to_excel(writer, index=False, sheet_name="PLC Tags")
                        
                        st.download_button(
                            label="📥 下載 TIA 變數表匯入檔 (.xlsx)", 
                            data=excel_buffer.getvalue(), 
                            file_name=f"PLC_Tags_{target_version}.xlsx", 
                            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            use_container_width=True,
                            key="dl_tags_btn"
                        )
                    except Exception as e:
                        st.error(f"變數表封裝失敗: {e}")
                
                st.markdown("#### 📊 TIA 全域變數預覽")
                try:
                    st.dataframe(df, use_container_width=True, hide_index=True)
                except:
                    pass
                
                st.divider()
                st.markdown("#### 🚀 部署至真實環境 (TIA Portal Openness)")
                
                is_create_mode = (st.session_state.global_tia_mode == "✨ 從無到有全新生成")
                tia_plc = st.session_state.global_tia_plc

                target_identifier = st.session_state.global_tia_proj if not is_create_mode else os.path.join(st.session_state.global_tia_dir, st.session_state.global_tia_new_name)
                
                msg_target = f"👉 **目標路徑**： `{target_identifier}`"
                msg_plc = f"👉 **設備名稱**： `{tia_plc}`"
                if is_create_mode:
                    msg_plc += f"\n\n👉 **硬體型號**： `{st.session_state.global_tia_mlfb_key}`"

                st.info(f"{msg_target}\n\n{msg_plc}\n\n*(若要修改請至畫面上方展開設定)*")
                
                if st.button("⚡ 一鍵自動寫入 TIA Portal", type="primary", use_container_width=True, key="tia_export_btn"):
                    if not tia_plc.strip():
                         st.warning("請在最上方填寫目標 PLC 名稱。")
                    elif not is_create_mode and not st.session_state.global_tia_proj.strip():
                         st.warning("請在最上方填寫完整的專案路徑。")
                    elif is_create_mode and (not st.session_state.global_tia_dir.strip() or not st.session_state.global_tia_new_name.strip()):
                         st.warning("請填寫目標存放資料夾與新專案名稱。")
                    else:
                        with st.spinner("正在與 TIA Portal 建立通訊，並在背景執行匯入 (約需 30~60 秒)..."):
                            temp_scl_path = os.path.abspath("temp_export.scl")
                            temp_tags_path = os.path.abspath("temp_tags.tsv")
                            try:
                                with open(temp_scl_path, "w", encoding="utf-8-sig") as f:
                                    f.write(scl_data['clean_scl'])
                                    
                                # 寫入 TSV 格式變數表供 C# 自動建置 Tags
                                try:
                                    if "df" in locals() and not df.empty:
                                        df.to_csv(temp_tags_path, sep='\t', index=False, encoding="utf-8-sig")
                                except Exception as e:
                                    st.warning(f"變數表匯出警告: {e}")
                                    temp_tags_path = None
                                    
                                exporter = TIAExporter()
                                
                                if is_create_mode:
                                     mlfb_str = plc_catalog.get(st.session_state.global_tia_mlfb_key, "")
                                     res = exporter.import_scl_to_tia(
                                         project_path_or_dir=st.session_state.global_tia_dir,
                                         scl_path=temp_scl_path,
                                         plc_name=tia_plc,
                                         tag_tsv_path=temp_tags_path,
                                         is_create_mode=True,
                                         project_name=st.session_state.global_tia_new_name,
                                         mlfb_string=mlfb_str
                                     )
                                else:
                                     res = exporter.import_scl_to_tia(
                                         project_path_or_dir=st.session_state.global_tia_proj,
                                         scl_path=temp_scl_path,
                                         plc_name=tia_plc,
                                         tag_tsv_path=temp_tags_path,
                                         is_create_mode=False
                                     )
                                
                                if res["success"]:
                                    st.success(f"🎉 {res['message']}")
                                    with st.expander("查看 TIA 背景執行紀錄"):
                                        st.code(res['details'], language="text")
                                else:
                                    st.error(f"❌ {res['message']}")
                                    if res.get('error'):
                                        st.error(f"錯誤原因:\n```text\n{res['error']}\n```")
                                    if res.get('details'):
                                        with st.expander("查看 TIA 背景執行紀錄"):
                                            st.code(res['details'], language="text")
                            finally:
                                if os.path.exists(temp_scl_path):
                                    os.remove(temp_scl_path)
                                if os.path.exists(temp_tags_path):
                                    os.remove(temp_tags_path)
            else:
                st.warning("程式碼生成失敗或遺失。")

        # --------- Tab 3: HMI 成果 ---------
        elif tab_selection == "🖥️ HMI 人機介面佈局":
            if "hmi" in pipeline_res:
                st.markdown("### 🎨 介面規劃師草圖")
                st.markdown("#### UI/UX 與變數對應表")
                st.info(pipeline_res["hmi"].tag_mapping)
                st.divider()
                st.markdown("#### 📐 ASCII 線框佈局圖 (Wireframe)")
                st.code(pipeline_res["hmi"].wireframe, language="text")
            else:
                st.info("本次生成無 HMI 結果。")
